# Generated by Django 2.2.6 on 2019-10-17 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atracoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Evento')),
                ('date', models.DateField(verbose_name='Data')),
                ('schedule', models.TimeField(verbose_name='Horario')),
                ('place', models.CharField(max_length=100, verbose_name='Local do evnto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('eventheld', models.BooleanField(default=False, verbose_name='Evento Realizado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('attraction', models.ManyToManyField(to='atracoes.Attraction', verbose_name='Atrações')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono do Evento')),
            ],
        ),
    ]
